apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  labels:
    app: checkout
    app.kubernetes.io/component: checkout
    app.kubernetes.io/instance: checkout
    app.kubernetes.io/name: checkout
    app.kubernetes.io/part-of: service-invocation
    app.openshift.io/runtime: nodejs
    app.openshift.io/runtime-version: 16-ubi8
  name: checkout
spec:
  failedBuildsHistoryLimit: 5
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: checkout:latest
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    contextDir: {{ .Values.global.build.contextDir }}/checkout
    git:
      uri: https://github.com/dapr/quickstarts.git
    type: Git
  strategy:
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: {{ .Values.global.build.s2i }}
        namespace: openshift
    type: Source
  successfulBuildsHistoryLimit: 5
  triggers:
  - generic:
      secretReference:
        name: checkout-generic-webhook-secret
    type: Generic
  - github:
      secretReference:
        name: checkout-github-webhook-secret
    type: GitHub
  - imageChange: {}
    type: ImageChange
  - type: ConfigChange