---
- name: Dapr System Installation
  hosts: localhost
  vars:
     helm_chart_url: 
      - { name: "dapr", url: "https://dapr.github.io/helm-charts/" }
      - { name: "redis", url: "https://charts.bitnami.com/bitnami" }
     dapr_version: 1.8.4
     dapr_namespace: dapr-system

  tasks:

    - name: Check if K8S is an Openshift instance
      kubernetes.core.k8s_info:
        api_version: config.openshift.io/v1
        kind: ClusterVersion
      register: is_ocp_k8s

    - debug: msg="Openshift {{ is_ocp_k8s.resources[0].spec.channel }} / {{ is_ocp_k8s.resources[0].status.desired.version }}"
      when: is_ocp_k8s.api_found

    - name: "Add all Helm Chart Repo "
      kubernetes.core.helm_repository:
        name: "{{ item.name }}"  
        repo_url: "{{ item.url }}"  
      with_items: "{{ helm_chart_url }}"

    - name: "Create {{ dapr_namespace }} namespace"
      kubernetes.core.k8s:
        name: "{{ dapr_namespace }}"
        api_version: v1
        kind: Namespace
        state: present

    - name: Install DAPR Chart
      kubernetes.core.helm:
        name: dapr
        namespace: "{{ dapr_namespace }}"
        chart_ref: dapr/dapr
        chart_version: "{{ dapr_version }}"
        update_repo_cache: true
        values:
          dapr_placement:
            logLevel: DEBUG
            cluster:
              forceInMemoryLog: true
            cluster.forceInMemoryLog: true
            runAsNonRoot: true
          dapr_sidecar_injector:
            logLevel: DEBUG
          dapr_sentry:
            runAsNonRoot: true
            logLevel: DEBUG

    - name: "Route for DAPR dashboard"
      kubernetes.core.k8s:
        name: dapr-dashboard
        api_version: v1
        kind: Route
        state: present
        namespace: "{{ dapr_namespace }}"
        definition:
          apiVersion: route.openshift.io/v1
          metadata:
            annotations:
              openshift.io/host.generated: 'true'
            labels:
              name: dapr-dashboard
          spec:
            to:
              kind: Service
              name: dapr-dashboard
              weight: 100
            port:
              targetPort: 8080
            wildcardPolicy: None
      when: is_ocp_k8s.api_found

    - name: "Gather information about DAPR {{ dapr_namespace }}"
      kubernetes.core.helm_info:
        name: dapr
        release_namespace: "{{ dapr_namespace }}"

    - name: "Get a list of all pods from {{ dapr_namespace }}"
      kubernetes.core.k8s_info:
        kind: Pod
        label_selectors:
          - app.kubernetes.io/name = dapr
          - app.kubernetes.io/part-of = dapr
      register: dapr_pod_list

    - debug: msg="Check {{ dapr_pod_list }} List"
      when: dapr_pod_list is defined    

    - name: Install Redis Helm Chart
      kubernetes.core.helm:
        name: redis 
        namespace: "{{ dapr_namespace }}"
        chart_ref: bitnami/redis
        update_repo_cache: true
        values:
          master:
            podSecurityContext:
              enabled: false
            containerSecurityContext:
              enabled: false
          replica:
            podSecurityContext:
              enabled: false
            containerSecurityContext:
              enabled: false

- name: Dapr Sample Installation
  hosts: localhost
  vars:
     app_namespace: dapr-application
     dapr_namespace: dapr-system
  tasks:

    - name: "Create {{ app_namespace }} namespace"
      kubernetes.core.k8s:
        name: "{{ app_namespace }}"
        api_version: v1
        kind: Namespace
        state: present

    - name: "Copy Secret from {{ dapr_namespace }}"
      kubernetes.core.k8s_info:
        kind: Secret
        name: redis
        namespace: "{{ dapr_namespace }}"
      register: redis_secret

    - name: "Paste Secret to {{ app_namespace }}"
      kubernetes.core.k8s:
        state: present
        definition:
          type: Opaque
          kind: Secret
          apiVersion: v1
          metadata:
            name: rediscopy
            namespace: "{{ app_namespace }}"
          data:
            "{{ redis_secret.resources[0].data }}"

    - name: Apply Redis DAPR integration
      kubernetes.core.k8s:
        state: present
        namespace: "{{ app_namespace }}"
        src: quickstarts/tutorials/hello-kubernetes/deploy/redis.yaml

    - name: add label to existing namespace
      kubernetes.core.k8s:
        state: patched
        kind: Component
        name: statestore
        definition:
          spec:
            metadata:
              - name: redisHost
                value: redis-master.dapr-system.svc.cluster.local:6379
              - name: redisPassword
                secretKeyRef:
                  name: redis
                  key: redis-password


    - name: Deploy Node.js app with the Dapr sidecar
      kubernetes.core.k8s:
        state: present
        namespace: "{{ app_namespace }}"
        src: quickstarts/tutorials/hello-kubernetes/deploy/node.yaml

    - name: Deploy Python app with the Dapr sidecar
      kubernetes.core.k8s:
        state: present
        namespace: "{{ app_namespace }}"
        src: quickstarts/tutorials/hello-kubernetes/deploy/python.yaml        

    - name: Deploy OrderProcessor app with the Dapr sidecar
      kubernetes.core.k8s:
        state: present
        namespace: "{{ app_namespace }}"
        src: service_invocation/javascript/http/k8s/order-processor.yaml

    - name: Deploy Checkout app with the Dapr sidecar
      kubernetes.core.k8s:
        state: present
        namespace: "{{ app_namespace }}"
        src: service_invocation/javascript/http/k8s/checkout.yaml
