apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: checkout
    app.kubernetes.io/component: checkout
    app.kubernetes.io/instance: checkout
    app.kubernetes.io/name: checkout
    app.kubernetes.io/part-of: service-invocation
    app.openshift.io/runtime: nodejs
    app.openshift.io/runtime-version: 16-ubi8
  name: checkout
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: checkout
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        dapr.io/app-id: checkout
        dapr.io/enable-api-logging: "true"
        dapr.io/enabled: "true"
        {{- if .Values.global.dapr.config }} 
        dapr.io/config: {{ .Values.global.dapr.config }} 
        {{- end }}
      labels:
        app: checkout
        deploymentconfig: checkout
    spec:
      containers:
      - image: {{ .Values.global.container.registry }}/{{ .Release.Namespace }}/checkout
        imagePullPolicy: Always
        name: checkout
        ports:
        - containerPort: 8080
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30