apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: checkout
  labels:
    app: checkout
    app.kubernetes.io/component: checkout
    app.kubernetes.io/instance: checkout
    app.kubernetes.io/name: checkout
    app.kubernetes.io/part-of: service-invocation
    app.openshift.io/runtime: nodejs
    app.openshift.io/runtime-version: 16-ubi8