apiVersion: dapr.io/v1alpha1
kind: Configuration
metadata:
  name: {{ .Values.pubsub.dapr_config }}
spec:
  features:
    - name: PubSub.Routing
      enabled: true
    - name: ServiceInvocation.NoDefaultContentType
      enabled: true