apiVersion: v1
data:
  datasource.yaml: |-
    apiVersion: 1

    datasources:
    - name: Prometheus
      type: prometheus
      url: https://thanos-querier.openshift-monitoring.svc.cluster.local:9091
      access: proxy
      basicAuth: false
      withCredentials: false
      isDefault: true
      jsonData:
        timeInterval: 5s
        tlsSkipVerify: true
        httpHeaderName1: "Authorization"
      secureJsonData:
        httpHeaderValue1: "Bearer {{ .Values.grafana.secret_token }}"
      editable: true
kind: ConfigMap
metadata:
  name: grafana-config

