kind: Deployment
apiVersion: apps/v1
metadata:
  name: sub-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sub-app
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: sub-app
      annotations:
        dapr.io/app-id: sub-app
        dapr.io/config: {{ .Values.pubsub.dapr_config }}
        dapr.io/enable-api-logging: 'true'
        dapr.io/enabled: 'true'
        dapr.io/app-port: "3000"
    spec:
      containers:
        - name: sub-app
          image: >-
            gautric/sub-app
          ports:
            - containerPort: 3000
              protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
