apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: order-processor
  labels:
    app: order-processor
    app.kubernetes.io/component: order-processor
    app.kubernetes.io/instance: order-processor
    app.kubernetes.io/name: order-processor
    app.kubernetes.io/part-of: service-invocation
    app.openshift.io/runtime: nodejs
    app.openshift.io/runtime-version: 16-ubi8