
tracing:
  samplingRate: "1"
  zipkin:
    namespace: dapr-system

global:
  dapr:
    config: service-invocation

  container:
    registry: image-registry.openshift-image-registry.svc:5000

  build:
    s2i: nodejs:16-ubi8
    contextDir: service_invocation/javascript/http
