apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: order-processor
    app.kubernetes.io/component: order-processor
    app.kubernetes.io/instance: order-processor
    app.kubernetes.io/name: order-processor
    app.kubernetes.io/part-of: service-invocation
    app.openshift.io/runtime: nodejs
    app.openshift.io/runtime-version: 16-ubi8
  name: order-processor
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: order-processor
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        dapr.io/app-id: order-processor
        dapr.io/app-port: "5001"
        dapr.io/enable-api-logging: "true"
        dapr.io/enabled: "true"
      labels:
        app: order-processor
        deploymentconfig: order-processor
    spec:
      containers:
#      - image: {{ .Release.Namespace }}/order-processor
      - image: {{ .Values.global.container.registry }}/{{ .Release.Namespace }}/order-processor
        imagePullPolicy: Always
        name: order-processor
        ports:
        - containerPort: 8080
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30