apiVersion: v1
items:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    labels:
      app: checkout
      app.kubernetes.io/component: checkout
      app.kubernetes.io/instance: checkout
      app.kubernetes.io/name: checkout
      app.kubernetes.io/part-of: service-invocation
      app.openshift.io/runtime: nodejs
      app.openshift.io/runtime-version: 16-ubi8
    name: checkout
  spec:
    progressDeadlineSeconds: 600
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        app: checkout
    strategy:
      rollingUpdate:
        maxSurge: 25%
        maxUnavailable: 25%
      type: RollingUpdate
    template:
      metadata:
        annotations:
          dapr.io/app-id: checkout
          dapr.io/enable-api-logging: "true"
          dapr.io/enabled: "true"
        labels:
          app: checkout
          deploymentconfig: checkout
      spec:
        containers:
        - image: image-registry.openshift-image-registry.svc:5000/dapr-sample/checkout
          imagePullPolicy: Always
          name: checkout
          ports:
          - containerPort: 8080
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
- apiVersion: build.openshift.io/v1
  kind: BuildConfig
  metadata:
    labels:
      app: checkout
      app.kubernetes.io/component: checkout
      app.kubernetes.io/instance: checkout
      app.kubernetes.io/name: checkout
      app.kubernetes.io/part-of: service-invocation
      app.openshift.io/runtime: nodejs
      app.openshift.io/runtime-version: 16-ubi8
    name: checkout
  spec:
    failedBuildsHistoryLimit: 5
    nodeSelector: null
    output:
      to:
        kind: ImageStreamTag
        name: checkout:latest
    postCommit: {}
    resources: {}
    runPolicy: Serial
    source:
      contextDir: service_invocation/javascript/http/checkout
      git:
        uri: https://github.com/dapr/quickstarts.git
      type: Git
    strategy:
      sourceStrategy:
        from:
          kind: ImageStreamTag
          name: nodejs:16-ubi8
          namespace: openshift
      type: Source
    successfulBuildsHistoryLimit: 5
    triggers:
    - generic:
        secretReference:
          name: checkout-generic-webhook-secret
      type: Generic
    - github:
        secretReference:
          name: checkout-github-webhook-secret
      type: GitHub
    - imageChange: {}
      type: ImageChange
    - type: ConfigChange
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    name: checkout
    labels:
      app: checkout
      app.kubernetes.io/component: checkout
      app.kubernetes.io/instance: checkout
      app.kubernetes.io/name: checkout
      app.kubernetes.io/part-of: service-invocation
      app.openshift.io/runtime: nodejs
      app.openshift.io/runtime-version: 16-ubi8
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
