apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: {{ .Values.pubsub.topic }}
  labels:
    strimzi.io/cluster: {{ .Values.pubsub.kafka_cluster_name }}
spec:
  partitions: 1
  replicas: 1
  config:
    retention.ms: 7200000
    segment.bytes: 1073741824
