kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: kafka-ui
  annotations:
    openshift.io/host.generated: 'true'
spec:
  to:
    kind: Service
    name: kafka-ui
    weight: 100
  port:
    targetPort: 8080
  wildcardPolicy: None
