kind: Service
apiVersion: v1
metadata:
  name: pub-app
spec:
  ipFamilies:
    - IPv4
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 3000
  internalTrafficPolicy: Cluster
  type: ClusterIP
  selector:
    app: pub-app
